config/routes.rb
Rails.application.routes.draw do
  resources :employees do
      #../employees/highest_salary
      collection do
          get "highest_salary"
      end
      #../employee/:id/full_salary
      member do
          get "full_salary"
      end
      #../employees/over_20k
      collection do
          get "over_20k"
      end
      
#    collection do
#        get "highest_salary"
#    end  
#      #../employee/:id/full_salary
#    member do
#        get "full_salary"
#    end
  end
    
    
#  get 'patients/show'
#
#  get 'patients/new'
#
#  get 'patients/create'
    
    #przy powyższych getach nie mamy id przy patients a przy resources mamy tak:
#    patients    POST /patients(.:format)     patients#create
#    new_patient GET  /patients/new(.:format) patients#new
#    patient     GET  /patients/:id(.:format) patients#show


    resources :patients, only: [:show, :new, :create]
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    
    scope :get_employee_with_highest_salary, -> { order("salary").last }
    scope :get_over_20k, -> (value = 20000) { where("salary>=:s", s: value)}
    
    def get_full_name
        self.name + " " + self.surname
    end
    
    def get_full_salary
        self.salary = 0 if self.salary.nil?
        self.commision = 0 if self.commision.nil?
        
        (self.salary - self.commision).to_s
    end
    
#    def self.get_employee_with_highest_salary
##        Employee.where("salary>=:salary", salary: 10000)
##        Employee.where("salary>= ?", 10000)
##        
#        Employee.all.order("salary").last
#    end
#    
#    def self.get_over_20k(value = 20000) # możemy podać jakąś wartość. domyślnie ustawione 20000 ale jak podamy inną to wywali inną
#        Employee.where("salary>=:s", s: value)
#    end
end

app/models/patient.rb
class Patient < ApplicationRecord
    def get_full_name
        self.name + " " + self.surname
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy, :full_salary]

    def highest_salary
        @employee = Employee.get_employee_with_highest_salary
        render 'show'
    end
    
    def full_salary
        render :show
    end
    
    def over_20k
#        @employees = Employee.get_over_20k(20000)
        @employees = Employee.get_over_20k
        render 'index'
    end

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :surname, :salary, :commision)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
      @patient = Patient.find(params[:id])
  end

  def new
      @patient = Patient.new
  end

  def create
      @patient = Patient.new(patient_params)
      if @patient.save
          redirect_to @patient, notice: 'Patient was successfully created'
        else
            render action: 'new'
      end
  end
    
    private
    
    def patient_params
        params.require(:patient).permit(:name, :surname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/employees/_form.html.erb
<%= form_for(employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <div class="field">
    <%= f.label :salary %>
    <%= f.number_field :salary %>
  </div>

  <div class="field">
    <%= f.label :commision %>
    <%= f.number_field :commision %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Salary</th>
      <th>Commision</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.surname %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.commision %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full Name:</strong>
  <%= @employee.get_full_name %>
</p>

<p>
  <strong>Full Salary:</strong>
  <%= @employee.get_full_salary %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Routing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/create.html.erb
<h1>Patients#create</h1>
<p>Find me in app/views/patients/create.html.erb</p>

app/views/patients/new.html.erb
<%= form_for(@patient) do |f| %>
    <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %><br>
    </div>
    <div class="field">
        <%= f.label :surname %><br>
        <%= f.text_field :surname %><br>
    </div>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/patients/show.html.erb
<%= @patient.get_full_name %>